package hw8.q4.backend.entities;

public enum StadiumName {
    AZADI,
    NAGHSHE_JAHAN,
    EMEAM_KHOMEINI,
    SHOHADAYE_GHODS,
    YADEGARE_EMAM,
    SOOLADSHAHR,
    DASTGERDI,
    EMAM_REZA,
    TAKHTI,
    FOOLAD_ARENA,
    GHASEM_SOLEIMANI_TABRIZ,
    GHASEM_SELEIMANI_SIRJAN,
    SHOHADAYE_MES,
    SHAHID_VATANI,
    SHAHID_MOHAMMADI
}
